" Install Plug                                                                                                                                                                                                                                                                                                                                                                                      
if empty(glob('~/.vim/autoload/plug.vim'))                                                                                                                                                                                                                                                                                                                                                          
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs                                                                                                                                                                                                                                                                                                                                          
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim                                                                                                                                                                                                                                                                                                                           
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC                                                                                                                                                                                                                                                                                                                                           
endif                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                    
call plug#begin()                                                                                                                                                                                                                                                                                                                                                                                   
" Fuzzy search                                                                                                                                                                                                                                                                                                                                                                                      
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }                                                                                                                                                                                                                                                                                                                                                 
Plug 'junegunn/fzf.vim'                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                    
" Linter                                                                                                                                                                                                                                                                                                                                                                                            
Plug 'dense-analysis/ale'                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                    
" " Color schemes                                                                                                                                                                                                                                                                                                                                                                                   
Plug 'nightsense/carbonized'                                                                                                                                                                                                                                                                                                                                                                        
Plug 'challenger-deep-theme/vim', { 'as': 'challenger-deep' }                                                                                                                                                                                                                                                                                                                                       
Plug 'Badacadabra/vim-archery'                                                                                                                                                                                                                                                                                                                                                                      
Plug 'junegunn/seoul256.vim'                                                                                                                                                                                                                                                                                                                                                                        
Plug 'endel/vim-github-colorscheme'                                                                                                                                                                                                                                                                                                                                                                 
Plug 'Yggdroot/indentLine'                                                                                                                                                                                                                                                                                                                                                                          
Plug 'morhetz/gruvbox'                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                    
" Display buffer number in command bar                                                                                                                                                                                                                                                                                                                                                              
Plug 'mihaifm/bufstop'                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                    
" Display status                                                                                                                                                                                                                                                                                                                                                                                    
Plug 'bling/vim-airline'                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                    
" Csv extension                                                                                                                                                                                                                                                                                                                                                                                     
Plug 'chrisbra/csv.vim'                                                                                                                                                                                                                                                                                                                                                                             
call plug#end()                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                    
set autoindent showmode showmatch smartindent                                                                                                                                                                                                                                                                                                                                                       
set tabstop=4 shiftwidth=4 expandtab softtabstop=4                                                                                                                                                                                                                                                                                                                                                  
syntax on                                                                                                                                                                                                                                                                                                                                                                                           
set nobackup nowritebackup                                                                                                                                                                                                                                                                                                                                                                          
set ignorecase                                                                                                                                                                                                                                                                                                                                                                                      
set number                                                                                                                                                                                                                                                                                                                                                                                          
set noswapfile                                                                                                                                                                                                                                                                                                                                                                                      
set hidden                                                                                                                                                                                                                                                                                                                                                                                          
colorscheme gruvbox                                                                                                                                                                                                                                                                                                                                                                                 
set bg=dark                                                                                                                                                                                                                                                                                                                                                                                         
set termguicolors                                                                                                                                                                                                                                                                                                                                                                                   
set wildmenu                                                                                                                                                                                                                                                                                                                                                                                        
set colorcolumn=101                                                                                                                                                                                                                                                                                                                                                                                 
set history=1000                                                                                                                                                                                                                                                                                                                                                                                    
set ruler                                                                                                                                                                                                                                                                                                                                                                                           
set showcmd                                                                                                                                                                                                                                                                                                                                                                                         
set scrolloff=5                                                                                                                                                                                                                                                                                                                                                                                     
set hlsearch                                                                                                                                                                                                                                                                                                                                                                                        
set incsearch                                                                                                                                                                                                                                                                                                                                                                                       
set smartcase                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                    
" Macros                                                                                                                                                                                                                                                                                                                                                                                            
let @p = 'Iimport pdb; pdb.set_trace()^['                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                    
" Remap Esc                                                                                                                                                                                                                                                                                                                                                                                         
inoremap jk <ESC>                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                    
" For auto complete                                                                                                                                                                                                                                                                                                                                                                                 
" For vim: Ctrl Space, Ctrl `                                                                                                                                                                                                                                                                                                                                                                       
inoremap <NUL> <C-n>                                                                                                                                                                                                                                                                                                                                                                                
" For nvim: Ctrl Space, Ctrl `                                                                                                                                                                                                                                                                                                                                                                      
inoremap <C-Space> <C-n>                                                                                                                                                                                                                                                                                                                                                                            
inoremap <C-n> <Nop>                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    
" For fuzzy search                                                                                                                                                                                                                                                                                                                                                                                  
nnoremap <C-p> :FZF<Space>/opt/ff/<CR>                                                                                                                                                                                                                                                                                                                                                              
nnoremap <C-p>. :FZF<Space>.<CR>                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                    
" For cycling buffers                                                                                                                                                                                                                                                                                                                                                                               
nnoremap <C-Left> :bprev<CR>                                                                                                                                                                                                                                                                                                                                                                        
nnoremap <C-Right> :bnext<CR>                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                    
" Termninal to normal mode (vim only)                                                                                                                                                                                                                                                                                                                                                               
" nvim version is in init.vim.                                                                                                                                                                                                                                                                                                                                                                      
tnoremap <Leader>t <C-w><S-n>                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                    
" Flag extra white space                                                                                                                                                                                                                                                                                                                                                                            
highlight ExtraWhitespace ctermbg=darkgreen guibg=lightgreen                                                                                                                                                                                                                                                                                                                                        
map <Leader>] :match ExtraWhitespace /\s\+$/<CR>                                                                                                                                                                                                                                                                                                                                                    
map <Leader>[ :match<CR>                                                                                                                                                                                                                                                                                                                                                                            
map <Leader>n :Bufstop<CR>                                                                                                                                                                                                                                                                                                                                                                          
map <Leader>m :BufstopModeFast<CR>                                                                                                                                                                                                                                                                                                                                                                  
map <Leader><BS> :noh<CR> 
